markdown: kramdown
paginate: 7
highlighter: pygments
safe: false
environment: dev
artifact_commit: dev
artifact_branch: master
asset_prefix: /asset
static_prefix: /static/dev
exclude:
- LICENSE
- README
