absolute: http://localhost:4000
title: Rik @ St Andrews
author: Rik Veenboer
email: rik.veenboer@gmail.com
disqus: boukefalos
analytics: UA-46375339-1
gems: [jekyll-paginate]
markdown: kramdown
paginate: 7
highlighter: pygments
safe: false
environment: dev
artifact_commit: dev
artifact_branch: master
asset_prefix: /asset
static_prefix: /static/dev
exclude:
- LICENSE
- README
