# location
absolute: http://csbnw.no-ip.org:3838
baseurl: .
asset_prefix: /asset
static_prefix: /static

# variables
title: Rik @ St Andrews
author: Rik Veenboer
email: rik.veenboer@gmail.com
github: https://github.com/boukefalos
disqus: boukefalos
analytics: UA-46375339-1
maps: AIzaSyCyIwGR-F48dFjAbwNr9JdOsfUYaUQxz1s

# pagination
paginate: 3
all_posts: 'Alle posts &rarr;'
all_posts_description: 'Bekijk alle # posts.'
read_more: '&raquo; Verder lezen...'
previous_page: '&larr; Vorige pagina'
next_page: 'Volgende pagina &rarr;'

# other
gems: [jekyll-paginate]
markdown: redcarpet
exclude:
- LICENSE
- README
environment: dev