# location
absolute: http://csbnw.no-ip.org:3838
baseurl: .
asset_prefix: /asset
static_prefix: /static

# variables
language: nl
title: Rik @ St Andrews
author: Rik Veenboer
email: rik.veenboer@gmail.com
github: https://github.com/boukefalos
disqus: boukefalos
analytics: UA-46375339-1
maps: AIzaSyCyIwGR-F48dFjAbwNr9JdOsfUYaUQxz1s
headers: [187b6ae, 54773b7, eae28bd]

# pagination
paginate: 15

# translations
all_posts: 'Alle # posts &rarr;'
read_more: '&raquo; Verder lezen...'
previous_page: '&larr; Vorige pagina'
next_page: 'Volgende pagina &rarr;'
mentioned_in: 'Komt voor in:'

# defaults
defaults:
  -
    scope:
      path: blog
      type: posts
    values:
      layout: post

# other
gems: [jekyll-paginate]
markdown: rdiscount
excerpt_separator: <a name="more"></a>
photo_sizes:
  - [1920, 1080]
  - [640, 0]
  - [200, 200]
  - [96, 96]
rdiscount:
    extensions: [smart]
exclude:
- LICENSE
- README