absolute: http://localhost
baseurl: jekyll
title: Rik @ St Andrews
author: Rik Veenboer
email: rik.veenboer@gmail.com
github: https://github.com/boukefalos
disqus: boukefalos
analytics: UA-46375339-1
gems: [jekyll-paginate]
markdown: kramdown
paginate: 7
highlighter: pygments
safe: false
environment: dev
artifact_commit: dev
artifact_branch: master
asset_prefix: /jekyll/asset
static_prefix: /jekyll/static
exclude:
- LICENSE
- README
